USE metabase_db;

-- Insert into Intents table
INSERT INTO Intents (
    intent_id,
    intent,
    confidence,
    keywords,
    products,
    issues,
    actions_of_agent,
    resolution_status,
    resolution,
    dominant_emotions_customer,
    conversation_sentiment,
    agent_professionalism,
    agent_performance,
    customer_satisfaction,
    callback_promise,
    callback_time
) VALUES
('INT001', 'Dispute Charge', 0.95, 'Arvind charged voice on my ... happens this time.', 'Credit Card', 'Duplicate charge: System error', 'Initiated a chargeback request and flagged for refund.', 'pending', 'N/A', 'frustration, anger', 'Negative', 'Agent remained calm and professional despite customer''s frustration.', 8, 4, FALSE, NULL),
('INT002', 'Billing Dispute', 0.95, 'Hey, I''ve been charged ... happens this time.', 'Credit Card', 'Duplicate charge: System error', 'Initiated a chargeback request and promised updates.', 'resolved', 'Chargeback request initiated; refund expected in 5-7 business days.', 'frustration, anger, urgency', 'Negative', 'Agent remained calm and empathetic despite customer''s frustration.', 8, 6, FALSE, NULL),
('INT003', 'Login Issue', 0.95, 'Hi I can''t login to invalid credentials', 'Savings Account', 'Unable to login: Invalid credentials, OTP not received: OTP system delayed', 'Verified registered mobile number and manually reset access, sending a temporary password.', 'resolved', 'Agent manually reset the customer''s access and sent a temporary password.', 'frustration, annoyance', 'Negative', 'Professional and empathetic.', 9, 7, FALSE, NULL),
('INT004', 'EMI Increase Dispute', 0.95, 'Your banks cheating me ... I am not paying extra.', 'Loan', 'Unexpected EMI increase: Floating interest rate increase due to RBI''s repo rate hike.', 'Agent apologized, reviewed the account, explained the reason for the increase, offered to explain EMI calculation, escalated to supervisor, and offered EMI moratorium option.', 'pending', 'N/A', 'anger, frustration', 'Negative', 'Agent remained calm and professional despite customer''s anger.', 7, 2, FALSE, NULL),
('INT005', 'Request to speak to manager', 0.90, 'You should do want ... speak to your manager.', 'Loan', NULL, 'Agent agreed to escalate the issue to the supervisor.', 'pending', 'N/A', 'anger, frustration', 'Negative', 'Agent remained calm and professional despite customer''s anger.', 7, 2, FALSE, NULL),
('INT006', 'Debit Card Issue', 0.95, 'Hello, my debit card ... what''s the deal?', 'Debit Card', 'Debit card declined at store: Insufficient funds in the account.', 'Verified card activity, identified insufficient funds, and initiated fund transfer from savings.', 'resolved', 'Funds transferred from savings to cover transaction amount.', 'frustration, surprise', 'Neutral', 'Professional and helpful.', 9, 8, FALSE, NULL),
('INT007', 'Aadhaar Linking Assistance', 0.95, 'Hello, I want to know and submit online which', 'Savings Account, Aadhaar', 'Difficulty linking Aadhaar to savings account: Customer unable to get help at the branch and unfamiliar with online processes.', 'Offered to guide through the process, provided options to visit the branch or send a form via email.', 'resolved', 'Agent offered to send a form to the customer''s email for online submission.', 'frustration, apprehension, gratitude', 'Positive', 'Professional and helpful.', 9, 9, FALSE, NULL),
('INT008', 'Report Fraudulent Transaction', 0.95, 'I got a fraud ... identite make', 'Credit Card', 'Unauthorized transaction: Card compromised', 'Blocked the card, filed a fraud report, and issued a replacement card.', 'resolved', 'Card blocked, fraud report filed, replacement card issued.', 'worried, anxious', 'Negative', 'Professional and empathetic.', 9, 8, TRUE, 'In 7 to 10 days'),
('INT009', 'Inquire About Refund', 0.90, 'But what about ... get it back?', 'Credit Card', NULL, 'Initiated a chargeback request and promised to follow up.', 'pending', 'N/A', 'concerned, hopeful', 'Neutral', 'Helpful and reassuring.', 9, 8, TRUE, 'In 7 to 10 days'),
('INT010', 'UPI Setup Assistance', 0.95, 'How do I set ... with my phone.', 'Savings Account, Mobile App, UPI', NULL, 'The agent provided instructions on how to set up UPI.', 'resolved', 'The agent provided the steps to set up UPI.', 'curious, positive', 'Positive', 'The agent was helpful and polite.', 9, 9, FALSE, NULL),
('INT011', 'Request EMI Moratorium', 0.95, 'I am trying to get and your website so confusing', 'Home Loan', 'Website is confusing: N/A', 'Agent apologized, asked for loan account number, checked eligibility.', 'resolved', 'Agent confirmed eligibility for 3-month moratorium.', 'frustration, relief', 'Positive', 'Professional and helpful.', 9, 9, FALSE, NULL),
('INT012', 'Inquire about CIBIL score impact', 0.98, 'Yes, please, but will affect my CIBIL score?', 'Home Loan', NULL, 'Agent clarified moratorium won''t directly impact CIBIL score but interest will accrue.', 'resolved', 'Agent explained CIBIL impact and offered to send detailed email.', 'anxiety, relief', 'Positive', 'Professional and informative.', 10, 10, FALSE, NULL),
('INT013', 'Card Activation', 0.95, 'I''ve been trying to send it.', 'Credit Card', 'Card activation failed through automated process: Unknown processing error.', 'Verified customer details and manually activated the card.', 'resolved', 'Agent manually activated the customer''s credit card.', 'frustration, impatience', 'Negative', 'Agent remained professional despite customer''s impatience.', 9, 7, FALSE, NULL),
('INT014', 'Confirmation Request', 0.90, 'Would you like to send it.', 'Credit Card', NULL, 'Offered to send a confirmation of activation.', 'resolved', 'Agent will send a confirmation to the customer.', 'relief', 'Positive', 'Professional and helpful.', 10, 9, FALSE, NULL),
('INT015', 'Technical Support', 0.95, 'I can''t set up and everytime I try.', 'Mobile Banking App', 'Mobile banking app crashing: Unknown, possibly outdated app version or compatibility issue.', 'Suggested uninstalling and reinstalling the app.', 'pending', 'N/A', 'frustration, impatience', 'Negative', 'Agent was polite and offered a solution.', 7, 4, FALSE, NULL),
('INT016', 'Check Loan Application Status', 0.95, 'Hello, I want to know weeks.', 'Loan', NULL, 'Checked the application status using customer''s name.', 'pending', 'N/A', 'anxious, impatient', 'Neutral', 'Professional and helpful.', 8, 6, FALSE, NULL),
('INT017', 'KYC Information Request', 0.90, 'approved but we need urgently.', 'Loan', 'Customer unaware of KYC requirement: Lack of communication from the branch.', 'Explained KYC and promised to send required documents via SMS.', 'pending', 'N/A', 'confused, frustrated', 'Negative', 'Professional and apologetic.', 9, 7, FALSE, NULL),
('INT018', 'Fraudulent Charge Reporting', 0.95, 'Your bank so mass my credit, see the refund in 7 to 10 days.', 'Credit Card', 'Unauthorized charge of $15000: Customer claims they did not make the transaction.', 'Verified transaction details, blocked the card, and initiated a chargeback request.', 'resolved', 'Chargeback request initiated; refund expected in 7-10 days.', 'frustration, anger', 'Negative', 'The agent remained calm and professional despite the customer''s frustration.', 9, 6, FALSE, NULL),
('INT019', 'NEFT Transfer Setup', 0.95, 'Hey, I just open my anything else.', 'Savings Account, NEFT Transfer', NULL, 'Provided instructions on how to set up NEFT transfer, including beneficiary details and activation time.', 'resolved', 'The agent explained the steps to set up NEFT transfer via the app and informed the customer about the 24-hour activation period.', 'Excitement, Gratitude', 'Positive', 'The agent was polite, helpful, and clear in their instructions.', 9, 10, FALSE, NULL),
('INT020', 'Account Issue - Lean on Account', 0.95, 'I paid my loan ... what''s going on?', 'Loan, EMI', 'Lean on account after EMI payment: System error', 'Identified the issue, confirmed payment processing, and removed the lean.', 'resolved', 'Lean was lifted and funds are available.', 'frustration, concern', 'Negative', 'Professional and empathetic.', 9, 8, FALSE, NULL),
('INT021', 'Check credit limit increase status', 0.95, 'I requested a credit ... what''s the hold up?', 'Credit Card', 'Delay in processing credit limit increase request: Request is under review.', 'Checked the status of the request and expedited it.', 'pending', 'N/A', 'frustration, impatience', 'Negative', 'Agent was polite and helpful.', 8, 6, FALSE, NULL),
('INT022', 'Expedite credit limit increase', 0.90, 'Tomorrow can''t you ... a big purchase.', 'Credit Card', NULL, 'Prioritized the request and promised an update by end of day.', 'pending', 'N/A', 'urgency, anxiety', 'Neutral', 'Agent was accommodating and tried to meet customer''s needs.', 9, 7, FALSE, NULL),
('INT023', 'Fraudulent Transaction Report', 0.95, 'I am worried my and stealing my money.', 'Savings Account', 'Unauthorized withdrawal of $25000: Customer did not authorize the transaction.', 'Froze the customer''s account, filed a fraud report, and assured transaction reversal.', 'pending', 'Transaction will be reversed within 5 to 7 days.', 'worried, scared', 'Negative', 'Agent was reassuring and took appropriate actions.', 9, 7, FALSE, NULL),
('INT024', 'Car Loan Application Issue', 0.95, 'I tried applying for and the application today.', 'Car Loan', 'Online application portal error: System glitch or incorrect document format', 'Suggested uploading documents in PDF format or offered manual processing.', 'resolved', 'Agent offered to process the application manually after receiving documents via email.', 'frustration, confusion', 'Neutral', 'Professional and helpful.', 9, 8, FALSE, NULL),
('INT025', 'Account Closure', 0.95, 'I want to close delaying it', 'Savings Account', 'Delay in account closure: Branch is delaying the process, Pending balance: 500 rupees pending balance', 'Verified account, offered options for pending balance, initiated closure and transfer.', 'resolved', 'Account closure and balance transfer initiated; confirmation to be sent.', 'frustration, impatience', 'Negative', 'Professional and empathetic.', 9, 7, FALSE, NULL),
('INT026', 'Loan Preclosure', 0.95, 'I am thrilled my...do next?', 'Loan', NULL, 'Confirmed loan account number and provided payment instructions.', 'resolved', 'Payment link sent to customer for outstanding balance.', 'Happy, Excited', 'Positive', 'Professional and helpful.', 9, 9, TRUE, NULL),
('INT027', 'Debit Card Issue', 0.95, 'Hello, my debit card ... what''s the deal?', 'Debit Card', 'Debit card declined at store: Insufficient funds in the account.', 'Verified card activity, identified insufficient funds, and enabled online transactions.', 'resolved', 'Online transactions enabled.', 'frustration, surprise', 'Neutral', 'Professional and helpful.', 9, 7, FALSE, NULL),
('INT028', 'Address Update', 0.95, 'I went to the branch ... it''s not done yet.', 'Bank Account', 'Address update not processed: Missing signature on the form.', 'Agent apologized, checked the status, identified the issue, and offered to email the form and expedite the update.', 'pending', 'N/A', 'frustration, annoyance', 'Negative', 'Professional and helpful.', 8, 6, FALSE, NULL),
('INT029', 'Dispute late fee', 0.95, 'You guys are reaping me off...for your mistak.', 'Loan', 'Late fee charged despite on-time payment: ECS mandate issue caused payment to be credited late.', 'Verified payment, identified ECS issue, waived the late fee, and apologized.', 'resolved', 'Late fee waived; updated statement available in 24 hours.', 'anger, frustration', 'Negative', 'Agent remained calm and professional despite customer''s anger.', 9, 6, FALSE, NULL),
('INT030', 'Card Activation', 0.95, 'I''ve been trying to send it.', 'Credit Card', 'Card activation failed through automated process: Unknown processing error.', 'Verified customer details and manually activated the card.', 'resolved', 'Agent manually activated the customer''s credit card.', 'frustration, impatience', 'Negative', 'Agent remained professional despite customer''s impatience.', 10, 10, FALSE, NULL),
('INT031', 'Inquiry about charge', 0.95, 'Does a 200 rupees about?', 'Savings Account', 'Unexpected charge of 200 rupees: Maintenance fee due to low balance', 'Identified the charge, explained the reason, and waived the fee.', 'resolved', 'Fee waived as a one-time courtesy.', 'frustration, inquiry', 'Negative', 'Professional and helpful.', 9, 7, FALSE, NULL),
('INT032', 'Balance Alert Setup', 0.80, 'I waive the fee for you.', 'Savings Account', NULL, 'Offered to set up balance alerts.', 'pending', 'N/A', NULL, 'Neutral', 'Proactive and helpful.', 8, 6, FALSE, NULL),
('INT033', 'Loan Payment Assistance', 0.95, 'I am freaking out my...updated you are all', 'Loan', 'Unable to access account to make loan payment: Unknown reason for account access issue, Concern about impact on credit score due to potential late payment: Customer worried about CIBIL score.', 'Offered manual payment processing or extending the due date and processed manual payment.', 'resolved', 'Manual payment processed and account updated.', 'anxious, stressed, worried', 'Positive', 'The agent was helpful and reassuring.', 9, 9, FALSE, NULL),
('INT034', 'Fixed Deposit Withdrawal', 0.95, 'I want to withdraw ... how does that work?', 'Fixed Deposit', 'Premature withdrawal penalty: Customer wants to withdraw before maturity.', 'Agent offered to calculate the reduced interest amount.', 'pending', 'N/A', 'anxious, urgent', 'Neutral', 'Professional and helpful.', 8, 7, FALSE, NULL),
('INT035', 'Report unauthorized transaction', 0.95, 'I got a bill and what''s going on?', 'Credit Card', 'Unauthorized transaction of $8000: Customer did not make the transaction.', 'Verified last four digits of the card, pledged to freeze the card, and initiated a dispute.', 'pending', 'N/A', 'worried, concerned', 'Negative', 'The agent responded empathetically and took appropriate actions.', 8, 7, FALSE, NULL),
('INT036', 'Inquire about refund timeframe', 0.90, 'how long till and money back.', 'Credit Card', NULL, 'Provided an estimated refund timeframe of 5 to 7 days and promised to keep the customer updated.', 'pending', 'N/A', 'anxious', 'Neutral', 'The agent provided a clear timeframe and offered to keep the customer updated.', 9, 8, FALSE, NULL),
('INT037', 'Account Access Issue', 0.95, 'I tried checking my ... account not found help.', 'Loan Account, Online Portal', 'Customer cannot access loan balance online: Account not linked to the online portal.', 'Agent confirmed the account number and linked the account to the portal. Agent also offered to send login instructions and a guide, and provided further assistance if needed.', 'resolved', 'Account linked to the portal and login instructions sent.', 'frustration, confusion', 'Negative', 'Professional and helpful.', 9, 8, FALSE, NULL),
('INT038', 'Assistance Request', 0.85, 'Ok but I am ... will it be easy?', 'Online Portal, Loan Account', 'Customer is not comfortable with online processes: Lack of familiarity with online systems.', 'Agent assured the customer that the process is simple and offered a guide and further assistance.', 'resolved', 'Agent provided reassurance and offered a guide and further support.', 'anxiety, uncertainty', 'Neutral', 'Patient and reassuring.', 10, 9, FALSE, NULL),
('INT039', 'Track RTGS Transfer', 0.95, 'I setup RTGS transfers and them.', 'RTGS Transfer', NULL, 'Agent confirmed the transfer was completed and provided options to track it.', 'resolved', 'Agent confirmed transfer completion and offered tracking options.', 'positive, inquisitive', 'Positive', 'Professional and helpful.', 9, 10, FALSE, NULL),
('INT040', 'Request Statement', 0.90, 'I want to make sure statement.', 'Bank Statement', NULL, 'Agent offered to send a statement to the customer''s email.', 'resolved', 'Agent sent the statement to the customer''s email.', 'positive, grateful', 'Positive', 'Professional and helpful.', 9, 10, FALSE, NULL),
('INT041', 'Billing Dispute', 0.95, 'Hey, I''ve been charged ... happens this time.', 'Credit Card', 'Unauthorized subscription charge: System error', 'Initiated a chargeback request and promised updates.', 'pending', 'N/A', 'frustration, anger', 'Negative', 'Agent remained calm and empathetic despite customer''s frustration.', 8, 4, FALSE, NULL),
('INT042', 'Card Issue', 0.95, 'Hello, I tried using the What''s wrong?', 'ATM Card', 'Card invalid at ATM: Card deactivated due to inactivity', 'Verified account, identified card status, reactivated card, and promised confirmation.', 'resolved', 'Card reactivated.', 'frustration, confusion', 'Negative', 'Professional and helpful.', 9, 8, FALSE, NULL),
('INT043', 'Check Loan Application Status', 0.95, 'Hello, I want to know weeks.', 'Loan', NULL, 'Checked the application status using customer''s name.', 'pending', 'N/A', 'anxious, impatient', 'Neutral', 'Professional and helpful.', 7, 4, FALSE, NULL),
('INT044', 'Escalation Request', 0.85, '48 hours can''t you ... business here.', 'Business Loan', 'Need for faster processing: Customer is losing business due to the delay.', 'Agent escalated the application for priority processing.', 'pending', 'N/A', 'frustration, urgency', 'Negative', 'Agent attempted to address the customer''s urgency.', 8, 6, FALSE, NULL),
('INT045', 'Rewards Redemption', 0.95, 'I just upgraded my and I am loving', 'Credit Card', NULL, 'The agent informed the customer about redeeming rewards via the app.', 'resolved', 'The agent directed the customer to the app''s rewards section.', 'Happy, Curious', 'Positive', 'The agent was polite and helpful.', 9, 9, TRUE, NULL),
('INT046', 'Fee Inquiry and Adjustment', 0.95, 'Why is there a ... avoid this in the future.', 'Savings Account', 'Customer was charged a 500 rupees penalty: Cheque bounce due to insufficient funds.', 'Investigated the account, identified the cheque bounce fee, and waived it as a one-time gesture. Agent also offered to set up alerts.', 'resolved', 'The agent waived the 500 rupees penalty.', 'frustration, disbelief', 'Negative', 'The agent was polite and helpful in resolving the issue.', 9, 8, FALSE, NULL),
('INT047', 'NPA Status Inquiry and Resolution', 0.95, 'I am so stressed my loan...reported to CIBIL', 'Loan Account', 'Loan account marked as NPA incorrectly: Payment was missed due to a bank error.', 'Confirmed account details, identified the cause of the NPA status, corrected the NPA status, and confirmed the account is clear and reported to CIBIL.', 'resolved', 'Agent corrected the NPA status due to a bank error.', 'stressed, worried', 'Negative', 'The agent was professional and helpful in resolving the issue.', 9, 8, FALSE, NULL),
('INT048', 'Open Demat Account', 0.95, 'I need to open, ... start trading so', 'Demat Account', NULL, 'Agent inquired about KYC documents, informed about processing time, and sent the form.', 'pending', 'N/A', 'Interested, Eager', 'Neutral', 'Professional and helpful.', 9, 8, TRUE, '2-3 days'),
('INT049', 'Payment Issue', 0.95, 'My card payment stuck... What''s the deal?', 'Card Payment', 'Payment stuck on processing: Payment gateway glitch', 'Identified the issue, offered to manually process the payment.', 'resolved', 'Agent manually processed the payment.', 'frustration, annoyance', 'Negative', 'Professional and helpful.', 9, 7, FALSE, NULL),
('INT050', 'EMI Inquiry', 0.95, 'My loan EMI is higher this month...why is it more now?', 'Loan', 'Unexpected increase in EMI amount: Floating interest rate and RBI rate hikes.', 'Agent apologized, asked for account number, explained floating rate and offered fixed rate option.', 'pending', 'N/A', 'Concern, Frustration', 'Negative', 'Professional and empathetic.', 8, 5, FALSE, NULL),
('INT051', 'Information Request', 0.90, 'I don''t understand this red stuff...explain it simply?', 'Loan', 'Customer doesn''t understand floating rates: Lack of understanding of financial terms.', 'Agent started to explain floating rates and offered to send a comparison.', 'pending', 'N/A', 'Confusion', 'Neutral', 'Professional and helpful.', 9, 7, FALSE, NULL),
('INT052', 'Increase Overdraft Limit', 0.95, 'I got an overdraft and it''s a limit?', 'Overdraft Facility', NULL, 'Agent asked for account number and requested customer to email documents.', 'pending', 'N/A', 'Happy, Eager', 'Positive', 'Professional and polite.', 7, 7, FALSE, NULL),
('INT053', 'Positive Feedback', 0.90, 'shooting this Bank great the way', 'Banking Services', NULL, 'Agent thanked the customer.', 'resolved', 'Agent acknowledged and appreciated the feedback.', 'Positive, Appreciative', 'Positive', 'Professional and polite.', 10, 10, FALSE, NULL),
('INT054', 'Debit Card Linking Issue', 0.95, 'My PPI wallet isn''t linking...What''s the problem?', 'PPI Wallet, Debit Card', 'Debit card not linking to PPI wallet: Card was not registered for PPI.', 'Verified card details, enabled PPI for the card, and expedited the activation.', 'resolved', 'Agent enabled PPI for the card, resolving the linking issue immediately.', 'frustration, urgency', 'Negative', 'Professional and helpful.', 9, 8, FALSE, NULL),
('INT055', 'Loan Closure Request', 0.95, 'I want to close my loan...What''s that about?', 'Loan', 'Need to fill out a closure request form: Branch informed the customer about the form requirement.', 'Agent offered to help, asked for the loan account number, and offered to email the form with instructions.', 'pending', 'N/A', 'frustration, confusion', 'Neutral', 'Professional and helpful.', 8, 6, FALSE, NULL),
('INT056', 'Information Request', 0.90, 'what''s for closure mean?...nobody explain it.', 'Loan', 'Lack of understanding of ''for closure'': Customer states nobody explained it.', 'Agent explained the meaning of foreclosure.', 'resolved', 'Agent explained that it means paying off the loan early.', 'confusion', 'Neutral', 'Professional and helpful.', 9, 8, FALSE, NULL),
('INT057', 'Billing Dispute', 0.95, 'Hey, I''ve been charged ... happens this time.', 'Credit Card', 'Erroneous fee charged: System error', 'Agent refunded the erroneous fee and promised updates.', 'resolved', 'Fee refunded; updated statement available in 24 hours.', 'frustration, anger', 'Negative', 'Agent remained calm and empathetic despite customer''s frustration.', 8, 4, FALSE, NULL),
('INT058', 'Account Closure Threat', 0.85, 'fix this or...closing my account', 'Bank Account', 'Potential account closure: Customer dissatisfied with erroneous charge', 'Addressed the billing issue to prevent account closure.', 'pending', 'N/A', 'anger, frustration', 'Negative', 'Agent attempted to resolve the issue to retain the customer.', 7, 3, FALSE, NULL),
('INT059', 'UPI Mandate Setup', 0.95, 'I just got my ... upi mandate?', 'Debit Card, UPI', NULL, 'The agent explained how to set up a UPI mandate via the app''s payment section and offered to walk the customer through the process.', 'resolved', 'The agent provided instructions, and the customer said they would try it themselves.', 'Positive, Curious', 'Positive', 'The agent was polite and helpful.', 9, 9, TRUE, NULL),
('INT060', 'Auto Payments Confirmation', 0.85, 'Nice is it ... like bill?', 'Debit Card, UPI, Auto Payments', NULL, 'The agent confirmed that it is for auto payments.', 'resolved', 'The agent confirmed the functionality.', 'Neutral', 'Positive', 'The agent was polite and helpful.', 9, 9, FALSE, NULL),
('INT061', 'Nominee Update', 0.95, 'I need to update the nominee...the nominee.', 'Savings Account', 'Customer needs to update nominee: Customer wants to add his son as nominee.', 'Agent informed customer about the nominee update form and offered to send it to the registered email.', 'pending', 'N/A', 'Neutral, Inquiry', 'Neutral', 'Agent was polite and provided information clearly.', 8, 6, FALSE, NULL),
('INT062', 'Payment Issue', 0.95, 'My card payment stuck... What''s the deal?', 'Card Payment', 'Payment stuck on processing: Payment gateway glitch', 'Identified the issue, offered to manually process the payment and updated CIBIL.', 'resolved', 'Agent manually processed the payment and updated CIBIL.', 'frustration, annoyance', 'Negative', 'Professional and helpful.', 9, 9, FALSE, NULL),
('INT063', 'Dispute Unauthorized Charge', 0.95, 'My credit card bills got ... paying for this nonsense.', 'Credit Card', 'Unauthorized $5000 charge: Merchant error', 'Agent verified card details, initiated dispute, blocked transactions.', 'resolved', 'Dispute filed, refund expected in 7-10 days.', 'frustration, anger', 'Negative', 'Professional and helpful.', 9, 8, FALSE, NULL),
('INT064', 'Technical Support', 0.95, 'I can''t set up and everytime I try.', 'Mobile Banking App', 'Net banking login issue: OTP not received', 'Suggested checking registered mobile number and resending OTP.', 'pending', 'N/A', 'frustration, impatience', 'Negative', 'Agent was polite and offered a solution.', 8, 7, FALSE, NULL),
('INT065', 'Account Inquiry', 0.95, 'I got a letter saying my overdue what''s happening?', 'Loan', 'Received overdue notice despite payment: System error caused payment not to reflect.', 'Verified account, identified system error, confirmed payment updated, and offered confirmation.', 'resolved', 'Payment status updated; confirmation to be sent.', 'confused, concerned', 'Neutral', 'Professional and reassuring.', 9, 8, FALSE, NULL),
('INT066', 'Increase Recurring Deposit Amount', 0.95, 'I set up a ... increase the amount?', 'Recurring Deposit', NULL, 'Agent asked for account number and provided information on how to modify the RD amount by submitting a form via email.', 'resolved', 'Agent sent the form to customer''s email.', 'happy, satisfied', 'Positive', 'Professional and helpful.', 9, 9, TRUE, NULL);


-- Insert into Calls table
INSERT INTO Calls (
    call_id,
    agent_id,
    duration,
    summary,
    num_intents,
    intent_1_id,
    intent_2_id,
    interruptions_by_customer,
    interruptions_by_agent
) VALUES
(1, 1, 59.0, 'Customer reported duplicate charge and requested a refund.', 1, 'INT001', NULL, 4, 0),
(2, 1, 58.0, 'Agent initiated chargeback for duplicate transaction and promised updates.', 1, 'INT002', NULL, 5, 2),
(3, 1, 37.0, 'Customer unable to login; agent reset access manually.', 1, 'INT003', NULL, 0, 0),
(4, 1, 38.0, 'Customer is upset about increased EMI and seeks resolution.', 2, 'INT004', 'INT005', 2, 0),
(5, 1, 34.88, 'Agent assisted customer with debit card decline issue.', 1, 'INT006', NULL, 0, 0),
(6, 1, 38.0, 'Agent assisted customer with Aadhaar linking to savings account.', 1, 'INT007', NULL, 0, 0),
(7, 1, 35.0, 'Agent assisted customer with fraudulent card transaction.', 2, 'INT008', 'INT009', 0, 0),
(8, 1, 23.92, 'Customer inquired about setting up UPI and was assisted.', 1, 'INT010', NULL, 0, 0),
(9, 1, 40.84, 'Customer requested EMI moratorium, agent checked eligibility and clarified concerns.', 2, 'INT011', 'INT012', 0, 0),
(10, 1, 33.84, 'Agent successfully activated customer''s credit card manually.', 2, 'INT013', 'INT014', 1, 0),
(11, 2, 28.0, 'Customer facing mobile banking app crashing issue.', 1, 'INT015', NULL, 0, 0),
(12, 2, 35.0, 'Customer inquires about loan application status and KYC process.', 2, 'INT016', 'INT017', 0, 0),
(13, 2, 29.0, 'Agent assisted customer with fraudulent credit card charge.', 1, 'INT018', NULL, 0, 0),
(14, 2, 27.0, 'Customer inquired about setting up NEFT transfer, resolved.', 1, 'INT019', NULL, 0, 0),
(15, 2, 33.0, 'Customer reports lean on account after EMI payment.', 1, 'INT020', NULL, 0, 0),
(16, 2, 30.0, 'Customer inquires about delayed credit limit increase request.', 2, 'INT021', 'INT022', 0, 0),
(17, 2, 28., 'Agent assisted customer with unauthorized transaction and secured account.', 1, 'INT023', NULL, 0, 0),
(18, 2, 28.0, 'Customer had issues applying for a car loan online.', 1, 'INT024', NULL, 0, 0),
(19, 2, 31.0, 'Agent assisted customer with savings account closure request.', 1, 'INT025', NULL, 0, 0),
(20, 2, 32.0, 'Customer inquires about loan preclosure final steps.', 1, 'INT026', NULL, 0, 0),
(21, 3, 28.0, 'Agent enabled online transactions for customer''s debit card.', 1, 'INT027', NULL, 0, 0),
(22, 3, 34.0, 'Customer address update delayed due to missing signature.', 1, 'INT028', NULL, 0, 0),
(23, 3, 32.0, 'Customer is upset about a late fee on loan.', 1, 'INT029', NULL, 1, 1),
(24, 3, 26.0, 'Customer successfully activated their new credit card with agent assistance.', 1, 'INT030', NULL, 0, 0),
(25, 3, 31.0, 'Customer inquires about unexpected charge, agent waives fee.', 2, 'INT031', 'INT032', 0, 0),
(26, 3, 30.0, 'Agent assisted customer with loan payment processing.', 1, 'INT033', NULL, 0, 0),
(27, 3, 32.0, 'Customer requests premature withdrawal of fixed deposit.', 1, 'INT034', NULL, 0, 0),
(28, 3, 26.6, 'The agent assisted with unauthorized card usage and dispute filing.', 2, 'INT035', 'INT036', 0, 0),
(29, 3, 30.0, 'Customer is unable to access loan balance online.', 2, 'INT037', 'INT038', 0, 0),
(30, 3, 30.0, 'Customer inquired about tracking an RTGS transfer.', 2, 'INT039', 'INT040', 0, 0),
(31, 4, 32.0, 'Customer is furious about unauthorized subscription charge.', 1, 'INT041', NULL, 0, 0),
(32, 4, 32.0, 'Agent reactivated customer''s card due to inactivity.', 1, 'INT042', NULL, 0, 0),
(33, 4, 31.0, 'Customer inquires about business loan application status, agent escalates.', 2, 'INT043', 'INT044', 0, 0),
(34, 4, 23.84, 'Customer inquired about redeeming credit card rewards, resolved quickly.', 1, 'INT045', NULL, 0, 0),
(35, 4, 30.0, 'Agent waived the cheque bounce fee and set up alerts.', 1, 'INT046', NULL, 1, 0),
(36, 4, 27.0, 'Agent resolved customer''s loan account NPA status concern.', 1, 'INT047', NULL, 0, 0),
(37, 4, 24.0, 'Agent assists customer in opening a demat account.', 1, 'INT048', NULL, 0, 0),
(38, 4, 24.0, 'Customer reports payment processing issue, agent resolves manually.', 1, 'INT049', NULL, 1, 0),
(39, 4, 30.0, 'Customer is concerned about a higher loan EMI payment.', 2, 'INT050', 'INT051', 1, 0),
(40, 4, 26.80, 'Customer wants to increase overdraft limit and praises bank.', 2, 'INT052', 'INT053', 1, 0),
(41, 5, 26.0, 'Customer''s PPI wallet wasn''t linking; agent resolved the issue.', 1, 'INT054', NULL, 1, 0),
(42, 5, 27.0, 'Customer wants to close loan and needs clarification.', 2, 'INT055', 'INT056', 0, 0),
(43, 5, 27.0, 'Agent refunded erroneous fee; customer threatened account closure.', 2, 'INT057', 'INT058', 0, 0),
(44, 5, 20.92, 'Customer inquired about setting up a UPI mandate.', 2, 'INT059', 'INT060', 0, 0),
(45, 5, 24.0, 'Customer wants to update nominee for savings account.', 1, 'INT061', NULL, 1, 0),
(46, 5, 26.64, 'Agent resolved customer''s loan payment issue and updated CIBIL.', 1, 'INT062', NULL, 0, 0),
(47, 5, 23.60, 'Customer reports and agent resolves unauthorized credit card charge.', 1, 'INT063', NULL, 0, 0),
(48, 5, 24.0, 'Customer unable to login to net banking, OTP not received.', 1, 'INT064', NULL, 0, 0),
(49, 5, 24.92, 'Agent resolved customer''s loan overdue notice issue.', 1, 'INT065', NULL, 0, 0),
(50, 5, 25.0, 'Customer wants to increase recurring deposit amount.', 1, 'INT066', NULL, 0, 0);

-- Insert into Agents table
INSERT INTO Agents (
    agent_id,
    chirp3_hd_voice,
    gender,
    num_customers_handled,
    avg_performance_score,
    avg_customer_satisfaction
) VALUES
(1, 'Autonoe', 'Female', 10, 8.71, 7.00),
(2, 'Sulafat', 'Female', 10, 8.75, 7.08),
(3, 'Erinome', 'Female', 10, 8.86, 7.86),
(4, 'Sadaltager', 'Male', 10, 8.54, 7.15),
(5, 'Schedar', 'Male', 10, 8.54, 7.23);